### ISSUE TITLE
one line is incomplete in Line 147

### ISSUE THREAD

**Issue by ShawnMiloGuo** [LSUESL/SeaDAS-Tools#1]
Thank you so much for sharing this code. Waiting for SeaDAS 7.5 so long for processing New Landsat 8 Collection 1 data. But it still no sign of release. With this code, SeaDAS 7.4 works well with USGS collection 1 datasets .

Little issuse:
In "convert_OLIbundle_from_C1.py",  Line 147 , it might be the code as follows:
bundle_files = [x for x in bundle_files if bad_ext not in x]

Thanks again for this awesome code!

**Comment by LSUESL** [comment]
Wow! Thank you for this; I think the Atom beautifier (and maybe a stray keystoke?) bit me there.

The code is repaired, and many thanks for the feedback!
